### ISSUE TITLE
difference from / to widgets

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/plugins#1]
How is this package different from your widgets package?

lol, l just love how you're one step ahead of what I'm doing! Thanks!

**Comment by kaidesu** [comment]
It's not different, really. Only thing different is the syntax when calling a widget vs. plugin. Widgets append `widget_` at the beginning while plugins do not append anything. They're very similar in the way they're executed but the use case is different. For instance, widgets should always return a view partial, but plugins should only return a data set (e.g. a `collection` of blog posts).

I _may_ end up merging the two into one package. I kinda threw this together to get a feel for the workflow and use-case.

**Comment by illuminate3** [comment]
Thanks!

Hmmm, just throwing out some thoughts.
What you just described sounds to me that this package is a "widget". So, I'd say to combine them then. 

packages > modules > plugins > widgets
However, everybody probably sees this different :smile:

**Comment by illuminate3** [comment]
Looks like I got stuck in the L 5.x to 5.1 changes...
(I'm still on L5.x until I can update my apps / modules)

Hmmm,
So, I shouldn't be using plugins to send data to a blade view?
And use widgets to do that instead?

**Comment by illuminate3** [comment]
gonna add my vespoken menu code as a reference:

my plugin (older type it seems ... :frowning: )

```
        Menu::handler('top')->hydrate(function()
            {
            $pages = Content::where('print_status_id', '=', 2)->orderBy('order')->get();
//dd($pages);
            return $pages;
            },
            function($children, $item)
            {
                if($item->depth < 1) {
                    $children->add($item->slug, $item->translate(Config::get('app.locale'))->title, Menu::items($item->as));
                }
            });

        return view("plugins.navigation_menu");
```

my main template call:

```
<ul class="nav navbar-nav">
{!!
    Plugin::MenuNavigation()
!!}
</ul>
```

my actual view:

```
<! -- Plugin -->

{!!
    Menu::handler('top')
        ->getItemsAtDepth(0);
!!}
```
